### PR TITLE
modify package check to prevent throwing

### LINKED ISSUE #766: error [cli-launch-master] Unexpected error during benchmark execution: Error: Cannot find module 'fabric-ca-client/package
## Context

benchmark fabric 2.0.0 with latest stable caliper image 0.3.0
## Expected Behavior

caliper container runs and generates loads into STU
## Actual Behavior

caliper    | added 545 packages from 191 contributors in 968.321s
caliper    | 2020.03.16-01:51:23.915 +0000 info  [cli-launch-master] Set workspace path: /hyperledger/caliper/workspace
caliper    | 2020.03.16-01:51:23.915 +0000 info  [cli-launch-master] Set benchmark configuration path: /hyperledger/caliper/workspace/benchmark/benchconfig.yaml
caliper    | 2020.03.16-01:51:23.916 +0000 info  [cli-launch-master] Set network configuration path: /hyperledger/caliper/workspace/benchmark/networkconfig.yaml
caliper    | 2020.03.16-01:51:23.916 +0000 info  [cli-launch-master] Set SUT type: fabric:latest
caliper    | 2020.03.16-01:51:24.037 +0000 info  [caliper-engine] Starting benchmark flow
caliper    | 2020.03.16-01:51:24.041 +0000 **error [cli-launch-master] Unexpected error during benchmark execution: Error: Cannot find module 'fabric-ca-client/package'**
caliper    | Usage:
caliper    |  caliper launch master --caliper-bind-sut fabric:1.4.1 [other options]
caliper    |
caliper    | Options:
caliper    |   --help, -h           Show usage information  [boolean]
caliper    |   --version            Show version information  [boolean]
caliper    |   --caliper-bind-sut   The name and version of the platform to bind to  [string]
caliper    |   --caliper-bind-cwd   The working directory for performing the SDK install  [string]
caliper    |   --caliper-bind-args  Additional arguments to pass to "npm install". Use the "=" notation when setting this parameter  [string]
caliper    |   --caliper-bind-file  Yaml file to override default (supported) package versions when binding an SDK  [string]
caliper    |
caliper    | { Error: Cannot find module 'fabric-ca-client/package'
caliper    |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
caliper    |     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
caliper    |     at Module.require (internal/modules/cjs/loader.js:692:17)
caliper    |     at require (internal/modules/cjs/helpers.js:25:18)
caliper    |     at new Fabric (/home/node/.npm-global/lib/node_modules/@hyperledger/caliper-cli/node_modules/@hyperledger/caliper-fabric/lib/fabric.js:32:32)
caliper    |     at CaliperEngine.adapterFactory (/home/node/.npm-global/lib/node_modules/@hyperledger/caliper-cli/node_modules/@hyperledger/caliper-fabric/lib/adapterFactory.js:26:19)
caliper    |     at CaliperEngine.run (/home/node/.npm-global/lib/node_modules/@hyperledger/caliper-cli/node_modules/@hyperledger/caliper-core/lib/master/caliper-engine.js:94:34)
caliper    |     at Function.handler (/home/node/.npm-global/lib/node_modules/@hyperledger/caliper-cli/lib/launch/lib/launchMaster.js:62:43)
caliper    |     at process._tickCallback (internal/process/next_tick.js:68:7) code: 'MODULE_NOT_FOUND' }
caliper exited with code 1
## Steps to Reproduce

1.  docker-compose up

The following is docker-compose.yaml file.

version: '2'

networks:
  caliper_net:
   external:
      name: net_byfn
services:
    caliper:
        container_name: caliper
        image: hyperledger/caliper:0.3.0
        environment:
        - CALIPER_BIND_SUT=fabric:latest
          #- CALIPER_BIND_SDK=1.4.7
        - CALIPER_PROJECTCONFIG=benchmark/caliper.yaml
        - CALIPER_BENCHCONFIG=benchmark/benchconfig.yaml
        - CALIPER_NETWORKCONFIG=benchmark/networkconfig.yaml
        # command for self building image hyperledger/caliper:0.2.0light, containing fabric replated initialization
        command: launch master
        volumes:
        - ./benchmark:/hyperledger/caliper/workspace/benchmark
        - ./invoke.js:/hyperledger/caliper/workspace/invoke.js
        - ../crypto-config:/hyperledger/caliper/workspace/config/crypto-config
        - /etc/hosts:/etc/hosts
        networks:
          - caliper_net

## Existing issues
No

## Context

With caliper image 0.3.0, intend to benchmark fabric 2.0.0.
## Your Environment

* image tag : hyperledger/caliper:0.3.0
* node version:  v12.16.1
* host operating system and version : ubuntu 18.04.3
* docker version： 19.03.5
* docker-compose version：1.17.1

### PR DESCRIPTION
**Pull request by nklincoln**
Signed-off-by: nkl199@yahoo.co.uk <nkl199@yahoo.co.uk>

Closes #766 and #765 

Modifies the package check within the fabric adaptor

### CODE REVIEW

File: packages/caliper-core/lib/common/utils/caliper-utils.js [hunk 1]
```diff
@@ -539,6 +539,21 @@ class CaliperUtils {
...
     }
 
+    /**
+     * Check if a named package is installed and accessible by caliper
+     * @param {string} packageName the name of the package to check
+     * @returns {boolean} boolean value for existence of accessible package
+     */
+    static packageIsInstalled(packageName) {
+        try {
+            require.resolve(packageName);
```
Comment (aklenik) [inline packages/caliper-core/lib/common/utils/caliper-utils.js]: This will tell whether the core package can see the queried package, not whether the caller can see it. This could lead to false reports for the caller. I overcame this by passing a `requireFunc` as an additional parameter, which defaults to `require` (of the caliper-utils module). This shouldn't be a problem for the internal packages (since they include the core deps), but 3rd party packages can run into problems when using this method.
